### ISSUE TITLE
node on android에서 apktool을 이용해 앱을 빌드할때 파일이나 디렉토리를 찾지못하는 문제

### ISSUE THREAD

**Issue by Mssuk** [kookmin-sw/2018-cap1-5#3]
정상적인 앱 빌드가 안되는 현상이 있습니다.(설치할수없는 앱)

**Comment by ghost** [comment]
symbolic link를 제대로 걸지 않아서 안됐었음(ln -s명령어로 해결)
ln -s {source directory} {destination directory}
