### ISSUE TITLE
chat-example chat 서버가 채팅입력을 받을 수 없는 문제

### ISSUE THREAD

**Issue by Mssuk** [kookmin-sw/2018-cap1-5#4]
채팅이 안쳐집니다. 원인파악과 해결 필요.

**Comment by hyungoo-kang-kmucs** [comment]
로컬에 저장되어 있는 라이브러리 파일
socket.io.js 그리고 jquery.js 을 로컬에 저장하여
javascript에서의 require함수 및 node.js 에서의 express를 통해 두 번 불러오는 방식으로 해결하였음.
