### ISSUE TITLE
ARM64프로세서에서만 돌아가는문제

### ISSUE THREAD

**Issue by ghost** [kookmin-sw/2018-cap1-5#5]
x86 등 다른 프로세서에서도 실행 가능하게 수정

**Comment by Mssuk** [comment]
참고: https://github.com/janeasystems/nodejs-mobile-samples/tree/master/android/native-gradle

Node.js on Mobile shared library  받을 수 있는 링크가 있음.

https://github.com/janeasystems/nodejs-mobile/releases/download/nodejs-mobile-v0.1.3/nodejs-mobile-v0.1.3-android.zip

arm64-v8a, armeabi-v7a, x86 ,x86_64 에 대한 libnode.so 파일 받을 수 있음.
이걸로 해결 가능할 지는 해봐야 알거같음

**Comment by Mssuk** [comment]
libnode.so 파일을 넣었으나 앱 강종당함,, 강종 안당하게 해주십쇼~~

**Comment by Mssuk** [comment]
정상적으로 구동되는 것 확인했습니다
